Global:
  DataSourceType: bq
  Parameters:
    - ParameterName: ds_start_date
      Description: date_from
      Type: Date
      Default: '2020-01-01'

QueryFiles:
  - Covid19:
      FileName: covid19_open_data.covid19_open_data.sql
      DataSourceType: bq
      Parameters:
        - ParameterName: ds_start_date
          Description: date_from
          Type: Date
          Default: '2020-01-01'
  - Bitcoin:
      FileName: crypto_bitcoin.transactions.sql
      Parameters:
        - ParameterName: ds_end_date
          Description: date_to
          Type: Date
          Default: '2020-12-31'
  - UsaNames:
      FileName: usa_names.usa_1910_2013.sql
      Parameters:
        - ParameterName: state
          Description: state of USA
          Type: String
          Default: 'WA'