# Type
# Name of parameter type. One of 'STRING', 'INT64', 'FLOAT64', 'NUMERIC', 'BOOL', 'TIMESTAMP', 'DATETIME', or 'DATE'

Global:
  DataSourceType: bq

QueryFiles:
  - covid19_open_data.covid19_open_data.sql:
      Parameters:
        - name: ds_start_date
          type: DATE
          value: '2020-01-01'
        - name: ds_end_date
          type: DATE
          value: '2020-01-31'
  - crypto_bitcoin.transactions.sql:
      Parameters:
        - name: ds_start_date
          type: DATE
          value: '2020-01-01'
        - name: ds_end_date
          type: DATE
          value: '2020-01-20'
  - usa_names.usa_1910_2013.sql:
      Parameters:
        - name: state
          type: STRING
          value: 'WA'